fx_version 'adamant'

game 'gta5'

author 'Snag'

description 'Weapon Meta\'s by Snag'

files {
  --Meta's used to balance weapons.
  'metas/vehicle_weapons/*.meta', 
  'metas/weapons/*.meta',
}

--  Vehicle weapon meta files
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapon_jb700.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapon_rctank.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapon_waterbomb.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_akula.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_annihilator2.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_apc.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_avenger.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_barrage.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_bombs.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_bombushka.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_bruiser.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_caracara.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_chernobog.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_deathbike.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_deluxo.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_dinghy5.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_dogfight.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_dune3.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_flame.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_hacker.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_halftrack.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_havok.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_hunter.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_issi4.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_khanjali.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_menacer.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_microlight.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_mine.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_mines.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_mines_rc.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_mogul.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_monster3.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_mortar.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_mule4.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_oppressor.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_oppressor2.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_paragon2.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_patrolboat.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_pounder2.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_rogue.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_scarab.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_scramjet.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_seabreeze.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_seasparrow2.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_speedo4.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_strikeforce.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_stromberg.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_submarine.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_tampa3.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_thruster.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_trailer.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_tula.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_vigilante.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_volatol.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_xmas17.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/vehicleweapons_xmas18.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/weaponairdefencegun.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/weaponcannonblazer.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/weapons_arena.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/weaponturretboxville.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/weaponturretinsurgent.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/weaponturretlimo.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/weaponturrettechnical.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/weaponturretvalkyrie.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/weaponvehicleruiner.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/vehicle_weapons/weaponvehiclesavage.meta'

---- Player weapon meta files.
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapon_ceramicpistol.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapon_combatshotgun.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapon_gadgetpistol.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapon_militaryrifle.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapon_navyrevolver.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponautoshotgun.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponbattleaxe.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponbottle.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponbullpuprifle.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponcombatpdw.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponcompactlauncher.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponcompactrifle.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapondagger.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapondbshotgun.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponfirework.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponflaregun.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponflashlight.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapongusenberg.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponhatchet.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponheavypistol.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponheavyshotgun.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponhominglauncher.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponknuckle.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponmachete.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponmachinepistol.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponmarksmanpistol.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponmarksmanrifle.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponminismg.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponmusket.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponpipebomb.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponpoolcue.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponproxmine.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponrailgun.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponrevolver.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapons.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapons_assaultrifle_mk2.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapons_bullpuprifle_mk2.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapons_carbinerifle_mk2.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapons_combatmg_mk2.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapons_doubleaction.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapons_heavysniper_mk2.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapons_marksmanrifle_mk2.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapons_pistol_mk2.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapons_pumpshotgun_mk2.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapons_revolver_mk2.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapons_smg_mk2.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapons_snspistol_mk2.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapons_spacerangers.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weapons_specialcarbine_mk2.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponsnowball.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponsnspistol.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponspecialcarbine.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponstonehatchet.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponswitchblade.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponvintagepistol.meta'
data_file 'WEAPONINFO_FILE_PATCH' 'metas/weapons/weaponwrench.meta'
